In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:/Users/0rame/Desktop/ML_tutorials/Datas/ticket_08_2017 - ticket_08_2017.csv")

C:\Users\0rame\AppData\Local\Temp\ipykernel_15416\241748869.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:/Users/0rame/Desktop/ML_tutorials/Datas/ticket_08_2017 - ticket_08_2017.csv")


# df = pd.read_csv("C:/Users/0rame/Desktop/ML_tutorials/Datas/ticket_08_2017 - ticket_08_2017.csv")

In [2]:
df1 =df.iloc[:,6:13]

In [3]:
df1.head()

sync_tkt_route_name  sync_tkt_schedule_no  sync_tkt_trip_no  \
0        CHRY-NEDKNDM                     1                 2   
1        CHRY-NEDKNDM                     1                 2   
2        CHRY-NEDKNDM                     1                 2   
3        CHRY-NEDKNDM                     1                 2   
4        CHRY-NEDKNDM                     1                 2   

  sync_tkt_start_stage_name sync_tkt_end_stage_name         sync_tkt_uid  \
0                 KATTAPANA               MARUKULAM  2017-07-31 14:43:35   
1                 KATTAPANA                  PARAPU  2017-07-31 14:43:35   
2                 KATTAPANA             KUTTIKANNAM  2017-07-31 14:43:35   
3                    SWARAJ             KUTTIKANNAM  2017-07-31 14:43:35   
4                MATTUKATTA             KUTTIKANNAM  2017-07-31 14:43:35   

   sync_tkt_full_count  
0                    1  
1                    1  
2                    1  
3                    1  
4                    1

In [4]:
df2 = df1.groupby(['sync_tkt_route_name','sync_tkt_schedule_no','sync_tkt_trip_no','sync_tkt_start_stage_name','sync_tkt_end_stage_name'],as_index=False).agg({'sync_tkt_full_count':'sum'})

In [5]:
df2

sync_tkt_route_name  sync_tkt_schedule_no  sync_tkt_trip_no  \
0            ANGLVLY-KTYM                     1                 1   
1            ANGLVLY-KTYM                     1                 1   
2            ANGLVLY-KTYM                     1                 1   
3            ANGLVLY-KTYM                     1                 1   
4            ANGLVLY-KTYM                     1                 1   
...                   ...                   ...               ...   
45745      VAIKOM-PNCHKAD                     3                 5   
45746      VAIKOM-PNCHKAD                     3                 6   
45747      VAIKOM-PNCHKAD                     3                 6   
45748      VAIKOM-PNCHKAD                     3                 7   
45749      VAIKOM-PNCHKAD                     3                 7   

      sync_tkt_start_stage_name sync_tkt_end_stage_name  sync_tkt_full_count  
0                         8MILE                MANIMALA                   13  
1                         8MILE                  PKALAM                    3  
2                     ALAMPALLY                   KPARA                    1  
3                     ALAMPALLY                MANIMALA                    1  
4                      CHETTEDA                MANIMALA                    3  
...                         ...                     ...                  ...  
45745                    VAIKOM              PUTANPALOM                    1  
45746                 KUMARAKOM                KOTTAYAM                    1  
45747                    VAIKOM              TALAYAZHOM                    1  
45748                    VAIKOM             KAVANATNKAR                    1  
45749                    VAIKOM                KOTTAYAM                    1  

[45750 rows x 6 columns]

In [39]:
x = df2.iloc[:,[0,1,2,3,4]].values

In [40]:
x

array([['ANGLVLY-KTYM', 1, 1, '8MILE', 'MANIMALA'],
       ['ANGLVLY-KTYM', 1, 1, '8MILE', 'PKALAM'],
       ['ANGLVLY-KTYM', 1, 1, 'ALAMPALLY', 'KPARA'],
       ...,
       ['VAIKOM-PNCHKAD', 3, 6, 'VAIKOM', 'TALAYAZHOM'],
       ['VAIKOM-PNCHKAD', 3, 7, 'VAIKOM', 'KAVANATNKAR'],
       ['VAIKOM-PNCHKAD', 3, 7, 'VAIKOM', 'KOTTAYAM']], dtype=object)

In [81]:
y = df2.iloc[:,[-1]].values
y

array([[13],
       [ 3],
       [ 1],
       ...,
       [ 1],
       [ 1],
       [ 1]], dtype=int64)

In [82]:
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [70]:
label1 = LabelEncoder()
x[:,0] = label1.fit_transform(x[:,0])

In [71]:
x

array([[0, 0, 0, 54, 736],
       [0, 0, 0, 54, 1067],
       [0, 0, 0, 71, 582],
       ...,
       [129, 2, 5, 1300, 1191],
       [129, 2, 6, 1300, 454],
       [129, 2, 6, 1300, 570]], dtype=object)

In [72]:
label2 = LabelEncoder()
x[:,1] = label2.fit_transform(x[:,1])

In [73]:
label3 = LabelEncoder()
x[:,2] = label3.fit_transform(x[:,2])

In [74]:
label4 = LabelEncoder()
x[:,3] = label4.fit_transform(x[:,3])

In [75]:
label5 = LabelEncoder()
x[:,4] = label5.fit_transform(x[:,4])

In [76]:
model = LinearRegression()

In [92]:
xtrain,xtest,ytrain,ytest = train_test_split(x, y)

In [83]:
xtrain.shape

(34312, 5)

In [84]:
ytrain.shape

(11438, 5)

In [89]:
xtest.shape

(34312, 1)

In [93]:
model.fit(xtrain,ytrain)

LinearRegression()

In [62]:
x.shape

(45750, 5)

In [91]:
ytest.shape

(11438, 1)

In [55]:
x[:,0].shape

(45750,)

In [56]:
x[:,1].shape

(45750,)

In [57]:
x[:,2].shape

(45750,)

In [58]:
x[:,3].shape

(45750,)

In [59]:
y.shape

(45750, 1)

In [85]:
y.shape

(45750, 1)

In [86]:
y.ndim

2

In [87]:
x.ndim


2

In [88]:
ytrain.ndim

2

In [94]:
ypred= model.predict(xtest)

In [95]:
ypred

array([[5.3472148 ],
       [6.38743062],
       [2.02026368],
       ...,
       [6.37210599],
       [6.57441462],
       [4.58374426]])

In [96]:
ytest

array([[ 1],
       [ 5],
       [ 2],
       ...,
       [ 2],
       [ 2],
       [21]], dtype=int64)

In [97]:
model.score(xtest,ytest)

0.01728256208157275